version: "3"
services:
  balanceador:
    image: haproxy:latest
    ports:
        - "443:443"
        - "8404:8404"
    networks:
      static-network:
        ipv4_address: 172.20.128.1
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      - APACHE_1_IP=172.20.128.3
      - APACHE_2_IP=172.20.128.4
      - APACHE_EXPOSED_PORT=8443
        
  db:
    image: mysql:8.0.19
    restart: always
    expose:
      - "3306"
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=virtuasthenics
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password

  app1:
    build: app1/.
    ports:
      - "8443:8443"
    expose:
      - "8443"
    links:
      - db
      - internal_service
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db/virtuasthenics?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=

  app2:
    build: app1/.
    expose:
      - "8443"
    links:
      - db
      - internal_service
    networks:
      static-network:
        ipv4_address: 172.20.128.4
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db/virtuasthenics?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  internal_service:
    build: app2/.
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      static-network:
        ipv4_address: 172.20.128.5
networks:
    static-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16